=== DevelopSys/CodigosUE/LM/codigos2526/XML/alumno.dtd
<!ELEMENT alumnos (alumno+,profesor)>
<!ELEMENT alumno (nombre, apellido, nota_media)>

<!ELEMENT profesor (nombre)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT nota_media (#PCDATA)>

=== DevelopSys/CodigosUE/LM/codigos2526/XML/alumnos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- definimos el dtd externo -->
<!DOCTYPE alumnos SYSTEM "alumno.dtd">
<!-- puedes escribir que esto no se renderiza -->
<!-- solo puede tener un nodo root -->
<alumnos>
	<!-- contenido del nodo alumnos -->
	<alumno>
		<nombre>
			Borja
		</nombre>
		<apellido>
			Martin
		</apellido>
		<nota_media>
			7.78
		</nota_media>
	</alumno>
	<alumno>
		<nombre>
			Maria
		</nombre>
		<apellido>
			Lopez
		</apellido>
		<nota_media>
			10
		</nota_media>
	</alumno>
	<alumno>
		<nombre>
			Julia
		</nombre>
		<apellido>
			Garcia
		</apellido>
		<nota_media>
			9
		</nota_media>
	</alumno>
	<profesor>
		<nombre>
			Juan
		</nombre>
	</profesor>
</alumnos>
